[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor="#ffffff"
backgroundColor="#050505"
secondaryBackgroundColor="#111111"
textColor="#000000"
font="sans serif"